--------------------------------------------------------
--  파일이 생성됨 - 금요일-9월-18-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence SEQ_PERSON
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_PERSON"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 10 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table PERSON
--------------------------------------------------------

  CREATE TABLE "PERSON" 
   (	"NUM" NUMBER(5,0), 
	"NAME" VARCHAR2(30 BYTE), 
	"BLOOD" VARCHAR2(10 BYTE), 
	"JAVA" NUMBER(5,0) DEFAULT 0, 
	"SPRING" NUMBER(5,0) DEFAULT 0, 
	"HEIGHT" NUMBER(6,1), 
	"BIRTHDAY" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PERSON2
--------------------------------------------------------

  CREATE TABLE "PERSON2" 
   (	"NUM" NUMBER(5,0), 
	"NAME" VARCHAR2(30 BYTE), 
	"BLOOD" VARCHAR2(10 BYTE), 
	"JAVA" NUMBER(5,0), 
	"SPRING" NUMBER(5,0), 
	"HEIGHT" NUMBER(6,1), 
	"BIRTHDAY" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PERSON3
--------------------------------------------------------

  CREATE TABLE "PERSON3" 
   (	"NUM" NUMBER(5,0), 
	"NAME" VARCHAR2(30 BYTE), 
	"BLOOD" VARCHAR2(10 BYTE), 
	"JAVA" NUMBER(5,0), 
	"SPRING" NUMBER(5,0), 
	"HEIGHT" NUMBER(6,1), 
	"BIRTHDAY" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table STU
--------------------------------------------------------

  CREATE TABLE "STU" 
   (	"NUM" NUMBER(5,0), 
	"NAME" VARCHAR2(30 BYTE), 
	"AGE" NUMBER(5,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into PERSON
SET DEFINE OFF;
Insert into PERSON (NUM,NAME,BLOOD,JAVA,SPRING,HEIGHT,BIRTHDAY) values (4,'강순자','b',80,90,170.8,to_date('75/09/22','RR/MM/DD'));
Insert into PERSON (NUM,NAME,BLOOD,JAVA,SPRING,HEIGHT,BIRTHDAY) values (3,'김미자','o',77,91,159.8,to_date('79/12/20','RR/MM/DD'));
Insert into PERSON (NUM,NAME,BLOOD,JAVA,SPRING,HEIGHT,BIRTHDAY) values (5,'최민수','ab',95,90,180.8,to_date('01/12/05','RR/MM/DD'));
Insert into PERSON (NUM,NAME,BLOOD,JAVA,SPRING,HEIGHT,BIRTHDAY) values (7,'수만','o',89,99,176.9,to_date('88/07/11','RR/MM/DD'));
Insert into PERSON (NUM,NAME,BLOOD,JAVA,SPRING,HEIGHT,BIRTHDAY) values (8,'만두','a',75,100,179.9,to_date('89/02/10','RR/MM/DD'));
Insert into PERSON (NUM,NAME,BLOOD,JAVA,SPRING,HEIGHT,BIRTHDAY) values (9,'우동','ab',72,88,180.9,to_date('94/03/16','RR/MM/DD'));
REM INSERTING into PERSON2
SET DEFINE OFF;
Insert into PERSON2 (NUM,NAME,BLOOD,JAVA,SPRING,HEIGHT,BIRTHDAY) values (1,'강호동','b',0,0,178.2,to_date('20/09/18','RR/MM/DD'));
Insert into PERSON2 (NUM,NAME,BLOOD,JAVA,SPRING,HEIGHT,BIRTHDAY) values (2,'이영자','b',78,90,156.8,to_date('78/12/20','RR/MM/DD'));
Insert into PERSON2 (NUM,NAME,BLOOD,JAVA,SPRING,HEIGHT,BIRTHDAY) values (4,'강순자','a',80,90,170.8,to_date('75/09/22','RR/MM/DD'));
Insert into PERSON2 (NUM,NAME,BLOOD,JAVA,SPRING,HEIGHT,BIRTHDAY) values (3,'김미자','o',77,91,159.8,to_date('79/12/20','RR/MM/DD'));
Insert into PERSON2 (NUM,NAME,BLOOD,JAVA,SPRING,HEIGHT,BIRTHDAY) values (5,'김철수','ab',88,90,180.8,to_date('01/12/05','RR/MM/DD'));
Insert into PERSON2 (NUM,NAME,BLOOD,JAVA,SPRING,HEIGHT,BIRTHDAY) values (6,'이순자','b',75,80,177.8,to_date('85/05/08','RR/MM/DD'));
REM INSERTING into PERSON3
SET DEFINE OFF;
Insert into PERSON3 (NUM,NAME,BLOOD,JAVA,SPRING,HEIGHT,BIRTHDAY) values (4,'강순자','a',80,90,170.8,to_date('75/09/22','RR/MM/DD'));
Insert into PERSON3 (NUM,NAME,BLOOD,JAVA,SPRING,HEIGHT,BIRTHDAY) values (3,'김미자','o',77,91,159.8,to_date('79/12/20','RR/MM/DD'));
REM INSERTING into STU
SET DEFINE OFF;
Insert into STU (NUM,NAME,AGE) values (1,'강호동',23);
Insert into STU (NUM,NAME,AGE) values (2,'이영자',34);
--------------------------------------------------------
--  DDL for Index SYS_C007008
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C007008" ON "PERSON" ("NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table PERSON
--------------------------------------------------------

  ALTER TABLE "PERSON" ADD PRIMARY KEY ("NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PERSON" ADD CONSTRAINT "CK_BLOOD" CHECK (BLOOD IN ('a','b','o','ab')) ENABLE;
  ALTER TABLE "PERSON" MODIFY ("NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PERSON2
--------------------------------------------------------

  ALTER TABLE "PERSON2" MODIFY ("NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PERSON3
--------------------------------------------------------

  ALTER TABLE "PERSON3" MODIFY ("NAME" NOT NULL ENABLE);
